name: gux
description: flutter gux framework

g2d_flutter:
  path: mod/g2d_flutter

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter

  intl: ^0.19.0
  http: ^0.13.3
  provider: ^6.0.0
  cupertino_icons: ^1.0.2
  image_picker: ^1.0.0
  photo_view: ^0.14.0
  table_calendar: ^3.1.2
  carousel_slider: ^5.0.0
  webview_flutter: ^4.0.0
  fl_chart: ^0.69.0
  flutter_ruler_picker: ^1.0.6
  custom_refresh_indicator: ^4.0.1
  flutter_osm_plugin: ^1.3.3+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.14.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "asset/logo.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true

  fonts:
    - family: gx-iconfont
      fonts:
        - asset: asset/font/iconfont.ttf

  assets:
    - asset/image/
    - asset/image/icon/
    - asset/image/common/
    - asset/image/widget/
    - asset/image/logo/
    - asset/image/app/trainimation/

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "asset/image/gux.png"

